import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // 1. Additive schema: create the authors tables and add the (nullable)
  //    `authors_id` relationship columns + FKs/indexes. The `users_fk`
  //    constraint and `users_id` index are dropped here, but the `users_id`
  //    COLUMN itself is kept until step 3 so step 2 can read it for the
  //    re-point. (Generated by `migrate:create`, minus the final two
  //    `DROP COLUMN "users_id"` statements, which move to step 3.)
  await db.execute(sql`
   CREATE TABLE "authors_socials" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"url" varchar NOT NULL
  );

  CREATE TABLE "authors" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"name" varchar NOT NULL,
  	"role" varchar,
  	"avatar_id" integer,
  	"bio" varchar,
  	"email" varchar,
  	"slug" varchar,
  	"slug_lock" boolean DEFAULT true,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );

  ALTER TABLE "posts_rels" DROP CONSTRAINT "posts_rels_users_fk";

  ALTER TABLE "_posts_v_rels" DROP CONSTRAINT "_posts_v_rels_users_fk";

  DROP INDEX "posts_rels_users_id_idx";
  DROP INDEX "_posts_v_rels_users_id_idx";
  ALTER TABLE "posts_rels" ADD COLUMN "authors_id" integer;
  ALTER TABLE "_posts_v_rels" ADD COLUMN "authors_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "authors_id" integer;
  ALTER TABLE "authors_socials" ADD CONSTRAINT "authors_socials_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "authors" ADD CONSTRAINT "authors_avatar_id_media_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "authors_socials_order_idx" ON "authors_socials" USING btree ("_order");
  CREATE INDEX "authors_socials_parent_id_idx" ON "authors_socials" USING btree ("_parent_id");
  CREATE INDEX "authors_avatar_idx" ON "authors" USING btree ("avatar_id");
  CREATE INDEX "authors_slug_idx" ON "authors" USING btree ("slug");
  CREATE INDEX "authors_updated_at_idx" ON "authors" USING btree ("updated_at");
  CREATE INDEX "authors_created_at_idx" ON "authors" USING btree ("created_at");
  ALTER TABLE "posts_rels" ADD CONSTRAINT "posts_rels_authors_fk" FOREIGN KEY ("authors_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_posts_v_rels" ADD CONSTRAINT "_posts_v_rels_authors_fk" FOREIGN KEY ("authors_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_authors_fk" FOREIGN KEY ("authors_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "posts_rels_authors_id_idx" ON "posts_rels" USING btree ("authors_id");
  CREATE INDEX "_posts_v_rels_authors_id_idx" ON "_posts_v_rels" USING btree ("authors_id");
  CREATE INDEX "payload_locked_documents_rels_authors_id_idx" ON "payload_locked_documents_rels" USING btree ("authors_id");`)

  // 2. Data: seed ONE site-owner author and re-point every existing byline
  //    from the (now-removed) users relation to it, so published posts render
  //    an identical `Brandon Perfetti` byline afterward. Values mirror
  //    src/lib/identity.ts at migration time (frozen here on purpose — a later
  //    identity edit must not retroactively rewrite this migration). Avatar is
  //    intentionally left empty (identity's image is a Cloudinary URL, not a
  //    Media doc); the byline shows name + role + social links.
  const author = await payload.create({
    collection: 'authors',
    req,
    // Never fire cache revalidation from inside a migration (no request
    // scope) — matches scripts/fix-migrated-posts.ts.
    context: { disableRevalidate: true },
    data: {
      name: 'Brandon Perfetti',
      slug: 'brandon-perfetti',
      role: 'Technical PM + Software Engineer',
      socials: [
        { url: 'https://x.com/brandonperfetti' },
        { url: 'https://github.com/brandonperfetti' },
        { url: 'https://www.linkedin.com/in/brandonperfetti/' },
      ],
    },
  })

  // Re-point published rows AND version-history rows (path = 'authors').
  await db.execute(sql`
  UPDATE "posts_rels"    SET "authors_id" = ${author.id}, "users_id" = NULL WHERE "path" = 'authors';
  UPDATE "_posts_v_rels" SET "authors_id" = ${author.id}, "users_id" = NULL WHERE "path" = 'authors';`)

  // 3. Now that no row references it, drop the legacy users linkage column.
  await db.execute(sql`
  ALTER TABLE "posts_rels" DROP COLUMN "users_id";
  ALTER TABLE "_posts_v_rels" DROP COLUMN "users_id";`)
}

export async function down({
  db,
  payload,
  req,
}: MigrateDownArgs): Promise<void> {
  // Reverses the schema only. The re-point in up() is not restorable (the
  // original per-post admin-user id is gone), so `users_id` comes back NULL and
  // bylines fall back to the `Brandon Perfetti` string — acceptable for a down.
  await db.execute(sql`
   ALTER TABLE "authors_socials" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "authors" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "authors_socials" CASCADE;
  DROP TABLE "authors" CASCADE;
  ALTER TABLE "posts_rels" DROP CONSTRAINT "posts_rels_authors_fk";
  
  ALTER TABLE "_posts_v_rels" DROP CONSTRAINT "_posts_v_rels_authors_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_authors_fk";
  
  DROP INDEX "posts_rels_authors_id_idx";
  DROP INDEX "_posts_v_rels_authors_id_idx";
  DROP INDEX "payload_locked_documents_rels_authors_id_idx";
  ALTER TABLE "posts_rels" ADD COLUMN "users_id" integer;
  ALTER TABLE "_posts_v_rels" ADD COLUMN "users_id" integer;
  ALTER TABLE "posts_rels" ADD CONSTRAINT "posts_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_posts_v_rels" ADD CONSTRAINT "_posts_v_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "posts_rels_users_id_idx" ON "posts_rels" USING btree ("users_id");
  CREATE INDEX "_posts_v_rels_users_id_idx" ON "_posts_v_rels" USING btree ("users_id");
  ALTER TABLE "posts_rels" DROP COLUMN "authors_id";
  ALTER TABLE "_posts_v_rels" DROP COLUMN "authors_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "authors_id";`)
}
