/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    projects: Project;
    'tech-stack': TechStack;
    uses: Use;
    categories: Category;
    tags: Tag;
    media: Media;
    users: User;
    authors: Author;
    'work-history': WorkHistory;
    redirects: Redirect;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'tech-stack': TechStackSelect<false> | TechStackSelect<true>;
    uses: UsesSelect<false> | UsesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'work-history': WorkHistorySelect<false> | WorkHistorySelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    identity: Identity;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    identity: IdentitySelect<false> | IdentitySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Page intro line under the headline (distinct from SEO).
   */
  subtitle?: string | null;
  hero: {
    /**
     * Controls what the hero renders above the page body. Blank draws nothing — use it when the headline lives in the Content tab (e.g. the About page). None, Standard, and Shader all render the Title, Subtitle, and the Hero text field below; Standard adds an image and Shader adds an animated background. If your headline/intro already live in the Content tab, choose Blank so they do not render twice.
     */
    type: 'blank' | 'none' | 'standard' | 'shader';
    /**
     * Full bleed runs the shader behind the header like the homepage; card keeps it inside a bounded panel.
     */
    presentation?: ('fullBleed' | 'card') | null;
    /**
     * shaders.com preset rendered behind the hero text.
     */
    shaderPreset?:
      ('northern-lights-2' | 'ribbon-flows-4' | 'synthesis-14' | 'drifting-lights-8' | 'static-noise-4') | null;
    /**
     * Home parity pulls the hero flush to the top with the homepage’s vertical rhythm (for a page meant to read like the homepage); standard keeps the page-builder default. Only affects the full-bleed treatment.
     */
    rhythm?: ('standard' | 'homeParity') | null;
    /**
     * How the page title animates in. Typewriter is the Home/About treatment; both fall back to static text under reduced motion.
     */
    headlineVariant?: ('line' | 'typewriter') | null;
    /**
     * Show the profile icon row under the hero, from the Identity global’s social links. Edit the list in Globals → Identity; per-page lists live in the Social links block instead.
     */
    showSocialLinks?: boolean | null;
    /**
     * Fade the subtitle and social row up on scroll, the way the homepage hero does. Off by default. Honors reduced motion (renders static). The headline keeps its own animation either way.
     */
    revealContent?: boolean | null;
    /**
     * Rich text shown inside the hero, below the subtitle. Rendered for None, Standard, and Shader; ignored when Type is Blank. Keep this distinct from the page body in the Content tab — putting the same copy in both renders it twice.
     */
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | ArticlesArchiveBlock
    | CallToActionBlock
    | CarouselBlock
    | ContactFormBlock
    | ContainerBlock
    | ContentBlock
    | FaqListBlock
    | FeatureCardGridBlock
    | HeadingBlock
    | ImageBlock
    | LeadBlock
    | LogoCarouselBlock
    | MediaBlock
    | NewsletterSignupBlock
    | PhotoStripBlock
    | ProseBlock
    | ShaderHeroBlock
    | SocialLinksBlock
    | SpacerBlock
    | StatsBlock
    | TestimonialsBlock
    | VideoEmbedBlock
    | WorkHistoryCardBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Hide the Share control on this entry (kill switch).
   */
  disableSharing?: boolean | null;
  /**
   * Force-enable these targets on top of the site default.
   */
  shareTargetsAdd?: ('x' | 'linkedin' | 'facebook' | 'reddit' | 'hackernews' | 'email' | 'copylink')[] | null;
  /**
   * Force-remove these targets from the site default.
   */
  shareTargetsRemove?: ('x' | 'linkedin' | 'facebook' | 'reddit' | 'hackernews' | 'email' | 'copylink')[] | null;
  /**
   * auto = follow the global generated-OG toggle · bespoke = always this entry’s own image · generated = always a generated card.
   */
  ogImageMode?: ('auto' | 'bespoke' | 'generated') | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short summary used on cards, RSS, and meta description fallback.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional page-builder sections rendered after the article body — CTA, newsletter signup, FAQ, related sections, and so on.
   */
  layout?:
    | (
        | ArticlesArchiveBlock
        | CallToActionBlock
        | CarouselBlock
        | ContactFormBlock
        | ContainerBlock
        | ContentBlock
        | FaqListBlock
        | FeatureCardGridBlock
        | HeadingBlock
        | ImageBlock
        | LeadBlock
        | LogoCarouselBlock
        | MediaBlock
        | NewsletterSignupBlock
        | PhotoStripBlock
        | ProseBlock
        | ShaderHeroBlock
        | SocialLinksBlock
        | SpacerBlock
        | StatsBlock
        | TestimonialsBlock
        | VideoEmbedBlock
        | WorkHistoryCardBlock
      )[]
    | null;
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Hide the Share control on this entry (kill switch).
   */
  disableSharing?: boolean | null;
  /**
   * Force-enable these targets on top of the site default.
   */
  shareTargetsAdd?: ('x' | 'linkedin' | 'facebook' | 'reddit' | 'hackernews' | 'email' | 'copylink')[] | null;
  /**
   * Force-remove these targets from the site default.
   */
  shareTargetsRemove?: ('x' | 'linkedin' | 'facebook' | 'reddit' | 'hackernews' | 'email' | 'copylink')[] | null;
  /**
   * auto = follow the global generated-OG toggle · bespoke = always this entry’s own image · generated = always a generated card.
   */
  ogImageMode?: ('auto' | 'bespoke' | 'generated') | null;
  publishedAt?: string | null;
  authors?: (number | Author)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  access: {
    visibility: 'public' | 'gated';
    /**
     * Clerk Billing plan slug (dormant until billing is enabled).
     */
    requiredPlan?: string | null;
    /**
     * Clerk feature flag (dormant until billing is enabled).
     */
    requiredFeature?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticlesArchiveBlock".
 */
export interface ArticlesArchiveBlock {
  heading?: string | null;
  /**
   * Card grid is up to three cards across, ending in a “Browse all articles” link. Stacked list is the home page treatment: one article per row with the hover overlay and the whole card clickable, and no browse link — pair it with a column for the home-page layout.
   */
  variant: 'grid' | 'stacked';
  /**
   * How many recent articles to show.
   */
  limit?: number | null;
  /**
   * Fade the articles up one after another as they scroll into view — the home-page treatment for the stacked list. Off by default. Honors reduced motion (renders static).
   */
  revealOnScroll?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articlesArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  /**
   * Cards render an image with a title and text; Media renders the image edge-to-edge. Both obey every behaviour knob below.
   */
  variant: 'cards' | 'media';
  slides?:
    | {
        image: number | Media;
        title?: string | null;
        text?: string | null;
        /**
         * Optional link the whole slide points to.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Slides shown at once on desktop (1–6). Fade always shows one.
   */
  slidesPerView?: number | null;
  /**
   * Slides shown at once on small screens.
   */
  slidesPerViewMobile?: number | null;
  /**
   * Slide moves the track horizontally; Fade cross-fades one slide at a time (a single slide per view). Reduced motion collapses Fade to Slide.
   */
  effect: 'slide' | 'fade';
  /**
   * Wrap from the last slide back to the first.
   */
  loop?: boolean | null;
  /**
   * Show previous / next arrows.
   */
  navigation?: boolean | null;
  /**
   * Show the pagination dots.
   */
  pagination?: boolean | null;
  /**
   * Advance slides automatically. Off by default, and always disabled for readers who prefer reduced motion.
   */
  autoplay?: boolean | null;
  /**
   * Milliseconds each slide dwells before autoplay advances (min 1000).
   */
  interval?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Optional section heading rendered above the card.
   */
  heading?: string | null;
  /**
   * Optional intro line under the heading.
   */
  intro?: string | null;
  /**
   * Retired placeholder — the form itself needs no configuration.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlock".
 */
export interface ContainerBlock {
  /**
   * Columns share a 12-column grid from the lg breakpoint up — two thirds plus one third fills a row, for example. They stack on smaller screens.
   */
  columns?: ColumnBlock[] | null;
  /**
   * Space between columns (and between them when stacked). Large widens from the lg breakpoint up to match the homepage’s two-column gutter.
   */
  gap: 'sm' | 'md' | 'lg' | 'homeParity';
  /**
   * How columns of different heights line up beside each other. A sticky column always aligns to the top.
   */
  verticalAlign: 'start' | 'center' | 'stretch';
  /**
   * How this section sits on the page: how wide it runs, how much air it carries, whether it can be linked to, and whether it renders at all.
   */
  section: {
    /**
     * Container keeps the page’s reading width. Full bleed escapes it edge to edge — the homepage photo-strip look.
     */
    width: 'container' | 'narrow' | 'fullBleed';
    /**
     * Extra space above and below the section, on top of the spacing its blocks already carry.
     */
    paddingY: 'none' | 'sm' | 'md' | 'lg';
    /**
     * Outer spacing above and below the section. Default keeps the compact rhythm every container has always had; Home matches the two-column rhythm of the hard-coded homepage grid.
     */
    rhythm?: ('default' | 'home') | null;
    /**
     * Optional. Makes the section linkable as #anchor — lowercase letters, numbers, hyphens and underscores, starting with a letter.
     */
    anchorId?: string | null;
    /**
     * Leaves the section out of the page entirely — not hidden with CSS, so its content never reaches the browser.
     */
    hidden?: boolean | null;
    /**
     * A curated zinc palette rather than a colour picker, so every section stays inside the design system and reads correctly in both light and dark. Backgrounds usually want some vertical padding above.
     */
    background: {
      /**
       * Paint the section with a flat tint or a two-stop gradient. None leaves the page background showing, as before.
       */
      style: 'none' | 'tint' | 'gradient';
      /**
       * Each tint carries its own light and dark value — pick by how much separation the section needs, not by colour.
       */
      tint?: ('subtle' | 'muted' | 'panel') | null;
      /**
       * Two zinc stops. Fade ends transparent, so the page background finishes the ramp.
       */
      gradient?: ('fade' | 'depth' | 'panel') | null;
      /**
       * Which way the gradient runs. Upwards reverses a ramp without needing a mirrored palette entry.
       */
      direction?: ('toBottom' | 'toTop' | 'toRight') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnBlock".
 */
export interface ColumnBlock {
  /**
   * Share of the 12-column grid from the lg breakpoint up. Every column is full width on smaller screens.
   */
  size: 'oneQuarter' | 'oneThird' | 'half' | 'twoThirds' | 'threeQuarters' | 'full';
  /**
   * Desktop only: from the lg breakpoint up this column follows the scroll beside its taller neighbour (the homepage rail). Below lg it stacks normally and nothing sticks.
   */
  sticky?: boolean | null;
  /**
   * Push this column’s content in from its left edge, from the lg breakpoint up. Rail gutter (lg:pl-16 xl:pl-24) matches the homepage right rail — pair it with a container gap of “Home parity” so the columns sit flush and the gutter falls between them.
   */
  contentInset?: ('none' | 'railGutter' | 'aboutRail') | null;
  /**
   * Show this everywhere (default), only on desktop (from the lg breakpoint up), or only on mobile (below lg). Use a desktop-only and a mobile-only copy to place the same block differently on each — the about-page portrait sits in the rail on desktop and inline on a phone.
   */
  visibility?: ('always' | 'desktopOnly' | 'mobileOnly') | null;
  /**
   * Fade each block in this column up one after another as it scrolls into view — the homepage rail treatment. Off by default. Honors reduced motion (renders static). Below the lg breakpoint it reveals the same way.
   */
  revealChildren?: boolean | null;
  content?:
    | (
        | ArticlesArchiveBlock
        | CallToActionBlock
        | CarouselBlock
        | ContactFormBlock
        | FaqListBlock
        | FeatureCardGridBlock
        | HeadingBlock
        | ImageBlock
        | LeadBlock
        | LogoCarouselBlock
        | MediaBlock
        | NewsletterSignupBlock
        | PhotoStripBlock
        | ProseBlock
        | SocialLinksBlock
        | SpacerBlock
        | StatsBlock
        | TestimonialsBlock
        | VideoEmbedBlock
        | WorkHistoryCardBlock
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'column';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqListBlock".
 */
export interface FaqListBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardGridBlock".
 */
export interface FeatureCardGridBlock {
  /**
   * Optional section heading rendered above the grid.
   */
  heading?: string | null;
  /**
   * Optional intro line under the heading.
   */
  intro?: string | null;
  cards?:
    | {
        /**
         * Optional icon (~96px square, SVG/PNG).
         */
        icon?: (number | null) | Media;
        eyebrow?: string | null;
        title: string;
        copy?: string | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureCardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock".
 */
export interface HeadingBlock {
  /**
   * Plain text — the animation splits it into words or characters, so formatting would not survive.
   */
  text: string;
  /**
   * The tag that gets rendered, and the size that goes with it. Pages usually carry one h1 — pick h2 for a section heading.
   */
  level: 'h1' | 'h2' | 'h3';
  /**
   * Typewriter is the home and about page treatment. Either way, visitors who prefer reduced motion get the finished heading with no animation at all.
   */
  variant: 'line' | 'typewriter';
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  /**
   * Alt text comes from the Media document, so it stays correct everywhere the asset is used.
   */
  media: number | Media;
  /**
   * Anything but "original" crops the image to fill the shape (object-cover).
   */
  aspect: 'auto' | 'square' | 'portrait' | 'video' | 'wide';
  rounded: 'none' | 'lg' | '2xl' | 'full';
  /**
   * A 3° rotation, the way the about-page portrait sits.
   */
  tilt: 'none' | 'left' | 'right';
  /**
   * Pad the image in from the left and right edges of the space it was given. "Extra small" (px-2.5, 10px a side) reproduces the breathing room the about-page portrait keeps inside its narrow rail.
   */
  inset: 'none' | 'xs';
  /**
   * Mobile only. "Full" (default) fills the width it is given. "Compact" centers the image at a small max-width on phones (mx-auto max-w-xs), then releases it to full width from the lg breakpoint up (lg:max-w-none) — the about-page portrait's compact-centered treatment. Desktop is identical to "Full".
   */
  size: 'full' | 'compact';
  /**
   * Uses the site hover treatment. Disabled automatically for visitors who prefer reduced motion, and on touch devices.
   */
  hoverScale?: boolean | null;
  /**
   * Turn on for the one image above the fold on this page — it is preloaded instead of lazy-loaded. More than one per page makes every one of them slower.
   */
  priority?: boolean | null;
  /**
   * Optional. Renders as a caption beneath the image.
   */
  caption?: string | null;
  /**
   * Show this everywhere (default), only on desktop (from the lg breakpoint up), or only on mobile (below lg). Use a desktop-only and a mobile-only copy to place the same block differently on each — the about-page portrait sits in the rail on desktop and inline on a phone.
   */
  visibility?: ('always' | 'desktopOnly' | 'mobileOnly') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadBlock".
 */
export interface LeadBlock {
  /**
   * The lead paragraph under a headline — the about page’s subtitle treatment. Plain text; for long-form body copy use the Prose block instead.
   */
  text: string;
  /**
   * Fade the paragraph up on scroll, the way the about page’s subtitle does. Off by default. Honors reduced motion (renders static).
   */
  reveal?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'lead';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCarouselBlock".
 */
export interface LogoCarouselBlock {
  logos?:
    | {
        /**
         * SVG or transparent PNG; displayed ~40px tall.
         */
        image: number | Media;
        /**
         * Optional hyperlink. Leave blank for no link.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Display height of each logo in pixels.
   */
  logoHeight?: number | null;
  layout?: ('scroll' | 'wrap') | null;
  /**
   * Marquee speed in pixels per second (0 disables).
   */
  scrollSpeed?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Existing content only. New images belong in the Image block, which adds cropping, corners, tilt, hover and the above-the-fold loading hint.
   */
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock".
 */
export interface NewsletterSignupBlock {
  /**
   * Optional section heading rendered above the card.
   */
  heading?: string | null;
  /**
   * Optional intro line under the heading.
   */
  intro?: string | null;
  /**
   * Retired placeholder — the signup card itself needs no configuration.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoStripBlock".
 */
export interface PhotoStripBlock {
  /**
   * Photos for the parallax strip — about five fills it best. On the Home page this block replaces the default gallery under the hero.
   */
  images: (number | Media)[];
  /**
   * Break the strip out of the reading column to the full viewport width — the homepage gallery placement. Off by default, so the strip stays inside the column like every other block.
   */
  fullBleed?: boolean | null;
  /**
   * Mark the first photo as the page’s priority image — use only when this strip is the largest thing above the fold (the homepage hero slot). Off by default so it competes with nothing.
   */
  priority?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'photoStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock".
 */
export interface ProseBlock {
  /**
   * Long-form body copy. Renders with exactly the typography an article body gets.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'prose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialLinksBlock".
 */
export interface SocialLinksBlock {
  /**
   * Icon row is the compact glyph strip under the home hero. Labeled list is the about-page rail: icon plus "Follow on …" text, one per line.
   */
  variant: 'iconRow' | 'labeledList';
  /**
   * Identity uses the profile URLs on the Identity global, so editing them there updates every page at once.
   */
  source: 'identity' | 'custom';
  /**
   * The icon is derived from the URL (X, GitHub, LinkedIn, Instagram, email — anything else gets a generic link glyph).
   */
  links?:
    | {
        /**
         * Profile URL, or an email address for a mail row (mailto: is added for you).
         */
        url: string;
        /**
         * Optional. Defaults to "Follow on <platform>" — the wording both pages use today.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The about-page treatment: a rule above a final mail row, set apart from the profile links.
   */
  showEmailDivider?: boolean | null;
  /**
   * Leave empty to use the address on the Identity global, so one edit there updates every page. Fill it in only when this page needs a different address. If both are empty the row is hidden rather than shown broken.
   */
  email?: string | null;
  /**
   * Show this everywhere (default), only on desktop (from the lg breakpoint up), or only on mobile (below lg). Use a desktop-only and a mobile-only copy to place the same block differently on each — the about-page portrait sits in the rail on desktop and inline on a phone.
   */
  visibility?: ('always' | 'desktopOnly' | 'mobileOnly') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socialLinks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  size: 'sm' | 'md' | 'lg';
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  items?:
    | {
        /**
         * e.g. "120+", "99.9%", "12 yrs"
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Grid lays the testimonials out as a responsive card grid; Carousel shows the same cards as a swipeable stacked-cards deck (autoplay off, reduced-motion safe).
   */
  layout?: ('grid' | 'carousel') | null;
  heading?: string | null;
  items?:
    | {
        quote: string;
        name: string;
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  /**
   * YouTube or Vimeo URL.
   */
  url: string;
  /**
   * Accessible title for the embed.
   */
  title: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkHistoryCardBlock".
 */
export interface WorkHistoryCardBlock {
  /**
   * Optional section heading rendered above the card.
   */
  heading?: string | null;
  /**
   * Optional intro line under the heading.
   */
  intro?: string | null;
  /**
   * Retired placeholder — the work-history card itself needs no configuration.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workHistoryCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShaderHeroBlock".
 */
export interface ShaderHeroBlock {
  /**
   * Existing content only. New shader sections belong in the page hero above (Hero type “Shader”, presentation “Card”), which draws this same panel and adds the headline, subtitle, links and social row.
   */
  preset: 'northern-lights-2' | 'ribbon-flows-4' | 'synthesis-14' | 'drifting-lights-8' | 'static-noise-4';
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'shaderHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Byline role/title, e.g. "Technical PM + Software Engineer".
   */
  role?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  email?: string | null;
  /**
   * Public profile URLs — surfaced as Article JSON-LD author.sameAs.
   */
  socials?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description?: string | null;
  /**
   * External URL (live site, repo, or case study).
   */
  link?: string | null;
  /**
   * Display label for the link (defaults to the hostname).
   */
  linkLabel?: string | null;
  logo?: (number | null) | Media;
  tech?: (number | TechStack)[] | null;
  featured?: boolean | null;
  year?: number | null;
  /**
   * Lower numbers sort first on /projects.
   */
  sortOrder?: number | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack".
 */
export interface TechStack {
  id: number;
  name: string;
  category: 'frontend' | 'framework' | 'backend' | 'testing' | 'data' | 'tooling' | 'ai';
  /**
   * Lucide icon name; leave empty to use the uploaded logo.
   */
  icon?: string | null;
  logo?: (number | null) | Media;
  proficiency?: ('daily' | 'proficient' | 'familiar' | 'exploring') | null;
  url?: string | null;
  /**
   * Optional single repo hint as owner/name (e.g. "vercel/next.js") — NOT a profile URL. The /tech activity badges come from an account-wide scan of the GITHUB_OWNER account; this field is only a fallback to match this entry to scan results when its display name differs from the package/topic name.
   */
  githubRepo?: string | null;
  notes?: string | null;
  featured?: boolean | null;
  /**
   * Lower numbers sort first on /tech.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uses".
 */
export interface Use {
  id: number;
  title: string;
  category: 'workstation' | 'development' | 'design' | 'podcasts' | 'productivity' | 'ai';
  description?: string | null;
  link?: string | null;
  /**
   * Optional link into the tech stack for the shared viz.
   */
  tech?: (number | null) | TechStack;
  /**
   * Lower numbers sort first within each /uses section.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-history".
 */
export interface WorkHistory {
  id: number;
  company: string;
  title: string;
  description?: string | null;
  logo?: (number | null) | Media;
  startDate: string;
  /**
   * Leave empty for a current role.
   */
  endDate?: string | null;
  current?: boolean | null;
  /**
   * Lower numbers sort first (most recent role on top).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  projects?: {
    /**
     * Allow clients to find projects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create projects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update projects.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete projects.
     */
    delete?: boolean | null;
  };
  techStack?: {
    /**
     * Allow clients to find tech-stack.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tech-stack.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tech-stack.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tech-stack.
     */
    delete?: boolean | null;
  };
  uses?: {
    /**
     * Allow clients to find uses.
     */
    find?: boolean | null;
    /**
     * Allow clients to create uses.
     */
    create?: boolean | null;
    /**
     * Allow clients to update uses.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete uses.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  tags?: {
    /**
     * Allow clients to find tags.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tags.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tags.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tags.
     */
    delete?: boolean | null;
  };
  workHistory?: {
    /**
     * Allow clients to find work-history.
     */
    find?: boolean | null;
    /**
     * Allow clients to create work-history.
     */
    create?: boolean | null;
    /**
     * Allow clients to update work-history.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete work-history.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'tech-stack';
        value: number | TechStack;
      } | null)
    | ({
        relationTo: 'uses';
        value: number | Use;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'work-history';
        value: number | WorkHistory;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  hero?:
    | T
    | {
        type?: T;
        presentation?: T;
        shaderPreset?: T;
        rhythm?: T;
        headlineVariant?: T;
        showSocialLinks?: T;
        revealContent?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        articlesArchive?: T | ArticlesArchiveBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        container?: T | ContainerBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        faqList?: T | FaqListBlockSelect<T>;
        featureCardGrid?: T | FeatureCardGridBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        lead?: T | LeadBlockSelect<T>;
        logoCarousel?: T | LogoCarouselBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        photoStrip?: T | PhotoStripBlockSelect<T>;
        prose?: T | ProseBlockSelect<T>;
        shaderHero?: T | ShaderHeroBlockSelect<T>;
        socialLinks?: T | SocialLinksBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        workHistoryCard?: T | WorkHistoryCardBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  disableSharing?: T;
  shareTargetsAdd?: T;
  shareTargetsRemove?: T;
  ogImageMode?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticlesArchiveBlock_select".
 */
export interface ArticlesArchiveBlockSelect<T extends boolean = true> {
  heading?: T;
  variant?: T;
  limit?: T;
  revealOnScroll?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  variant?: T;
  slides?:
    | T
    | {
        image?: T;
        title?: T;
        text?: T;
        href?: T;
        id?: T;
      };
  slidesPerView?: T;
  slidesPerViewMobile?: T;
  effect?: T;
  loop?: T;
  navigation?: T;
  pagination?: T;
  autoplay?: T;
  interval?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlock_select".
 */
export interface ContainerBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        column?: T | ColumnBlockSelect<T>;
      };
  gap?: T;
  verticalAlign?: T;
  section?:
    | T
    | {
        width?: T;
        paddingY?: T;
        rhythm?: T;
        anchorId?: T;
        hidden?: T;
        background?:
          | T
          | {
              style?: T;
              tint?: T;
              gradient?: T;
              direction?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnBlock_select".
 */
export interface ColumnBlockSelect<T extends boolean = true> {
  size?: T;
  sticky?: T;
  contentInset?: T;
  visibility?: T;
  revealChildren?: T;
  content?:
    | T
    | {
        articlesArchive?: T | ArticlesArchiveBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        faqList?: T | FaqListBlockSelect<T>;
        featureCardGrid?: T | FeatureCardGridBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        lead?: T | LeadBlockSelect<T>;
        logoCarousel?: T | LogoCarouselBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        photoStrip?: T | PhotoStripBlockSelect<T>;
        prose?: T | ProseBlockSelect<T>;
        socialLinks?: T | SocialLinksBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        workHistoryCard?: T | WorkHistoryCardBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqListBlock_select".
 */
export interface FaqListBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardGridBlock_select".
 */
export interface FeatureCardGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  cards?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
        copy?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock_select".
 */
export interface HeadingBlockSelect<T extends boolean = true> {
  text?: T;
  level?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  media?: T;
  aspect?: T;
  rounded?: T;
  tilt?: T;
  inset?: T;
  size?: T;
  hoverScale?: T;
  priority?: T;
  caption?: T;
  visibility?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadBlock_select".
 */
export interface LeadBlockSelect<T extends boolean = true> {
  text?: T;
  reveal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCarouselBlock_select".
 */
export interface LogoCarouselBlockSelect<T extends boolean = true> {
  logos?:
    | T
    | {
        image?: T;
        url?: T;
        id?: T;
      };
  logoHeight?: T;
  layout?: T;
  scrollSpeed?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock_select".
 */
export interface NewsletterSignupBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoStripBlock_select".
 */
export interface PhotoStripBlockSelect<T extends boolean = true> {
  images?: T;
  fullBleed?: T;
  priority?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock_select".
 */
export interface ProseBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialLinksBlock_select".
 */
export interface SocialLinksBlockSelect<T extends boolean = true> {
  variant?: T;
  source?: T;
  links?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  showEmailDivider?: T;
  email?: T;
  visibility?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  layout?: T;
  heading?: T;
  items?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  url?: T;
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkHistoryCardBlock_select".
 */
export interface WorkHistoryCardBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShaderHeroBlock_select".
 */
export interface ShaderHeroBlockSelect<T extends boolean = true> {
  preset?: T;
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  layout?:
    | T
    | {
        articlesArchive?: T | ArticlesArchiveBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        container?: T | ContainerBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        faqList?: T | FaqListBlockSelect<T>;
        featureCardGrid?: T | FeatureCardGridBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        lead?: T | LeadBlockSelect<T>;
        logoCarousel?: T | LogoCarouselBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        photoStrip?: T | PhotoStripBlockSelect<T>;
        prose?: T | ProseBlockSelect<T>;
        shaderHero?: T | ShaderHeroBlockSelect<T>;
        socialLinks?: T | SocialLinksBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        workHistoryCard?: T | WorkHistoryCardBlockSelect<T>;
      };
  relatedPosts?: T;
  categories?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  disableSharing?: T;
  shareTargetsAdd?: T;
  shareTargetsRemove?: T;
  ogImageMode?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  access?:
    | T
    | {
        visibility?: T;
        requiredPlan?: T;
        requiredFeature?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  link?: T;
  linkLabel?: T;
  logo?: T;
  tech?: T;
  featured?: T;
  year?: T;
  sortOrder?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack_select".
 */
export interface TechStackSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  icon?: T;
  logo?: T;
  proficiency?: T;
  url?: T;
  githubRepo?: T;
  notes?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uses_select".
 */
export interface UsesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  link?: T;
  tech?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  email?: T;
  socials?:
    | T
    | {
        url?: T;
        id?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-history_select".
 */
export interface WorkHistorySelect<T extends boolean = true> {
  company?: T;
  title?: T;
  description?: T;
  logo?: T;
  startDate?: T;
  endDate?: T;
  current?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  projects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  techStack?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  uses?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  tags?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  workHistory?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Canonical origin (e.g. https://brandonperfetti.com). Falls back to NEXT_PUBLIC_SITE_URL.
   */
  canonicalUrl?: string | null;
  defaultSeo?: {
    title?: string | null;
    /**
     * Default meta description. Empty → the built-in site description.
     */
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show the Copy-page button on articles.
   */
  copyPageEnabled?: boolean | null;
  /**
   * Button label. Empty → "Copy page".
   */
  copyPageLabel?: string | null;
  /**
   * Globally enabled share destinations (desktop modal). Copy-link is the floor.
   */
  shareTargets?: ('x' | 'linkedin' | 'facebook' | 'reddit' | 'hackernews' | 'email' | 'copylink')[] | null;
  /**
   * Global toggle for dynamic generated OG title-cards (T7).
   */
  generatedOgEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  name: string;
  jobTitle?: string | null;
  /**
   * Public contact address. The Social Links block’s divider row uses it unless that block overrides it; leave this empty and no page shows an address at all.
   */
  email?: string | null;
  image?: (number | null) | Media;
  /**
   * CV file (PDF) served by the “Download CV” button on the home-page Work card. Upload a fresh copy here whenever the resume changes — no deploy needed.
   */
  resume?: (number | null) | Media;
  /**
   * Social profile URLs for the Person schema sameAs list.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  canonicalUrl?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyPageEnabled?: T;
  copyPageLabel?: T;
  shareTargets?: T;
  generatedOgEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  name?: T;
  jobTitle?: T;
  email?: T;
  image?: T;
  resume?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?:
    | (
        | 'typescript'
        | 'javascript'
        | 'tsx'
        | 'jsx'
        | 'css'
        | 'html'
        | 'json'
        | 'yaml'
        | 'bash'
        | 'sql'
        | 'markdown'
        | 'python'
        | 'graphql'
        | 'dockerfile'
        | 'diff'
        | 'none'
      )
    | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}